### ISSUE TITLE
게임에 어울리는  셰이더 제작

### ISSUE THREAD

**Issue by blAs1N** [team-sosweet/Saucewich#54]

**Comment by chan328** [comment]
https://l.messenger.com/l.php?u=http%3A%2F%2Fblog.theoroy.com%2F2017%2F04%2F27%2Fanime-look-cel-shading-in-ue4%2F&h=AT2LgFtWDynINDKLDhlXfPlU7lVuooDQas7Wh6TixJfG44mEKrICTv4GuYUrD1bPNEXLKfYeMNwh0_rlmf4Wng31tDdeSaFqrda5znwCCra8UgnmLA9B7CALE-VxFUCPAcnN2w

**Comment by chan328** [comment]
Cel shader는 완성
